agregar despliegue ms-catalogo

diff --git a/.github/workflows/produccion.yml b/.github/workflows/produccion.yml
--- a/.github/workflows/produccion.yml
+++ b/.github/workflows/produccion.yml
@@ -34,8 +34,69 @@ jobs:
           cd Biblioteca-Springboot
           mvn clean install -DskipTests
 
+      # 4. Copiar Eureka a AWS
+      - name: Copiar Eureka
+        uses: appleboy/scp-action@v0.1.7
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USER }}
+          key: ${{ secrets.SSH_KEY }}
+          port: ${{ secrets.SSH_PORT }}
+          source: "Biblioteca-Springboot/eureka/target/cl-triskeledu-eureka-1.0-SNAPSHOT.jar"
+          target: "/home/ubuntu/Deploy"
+          strip_components: 3
 
-      # 4. Copiar ms-usuarios a AWS
+      # 5. Preparar y ejecutar Eureka
+      - name: Preparar y ejecutar Eureka
+        uses: appleboy/ssh-action@v1.2.2
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USER }}
+          key: ${{ secrets.SSH_KEY }}
+          port: ${{ secrets.SSH_PORT }}
+          script: |
+            cd /home/ubuntu/Deploy
+
+            echo "Deteniendo Eureka anterior..."
+
+            if [ -f eureka.pid ]; then
+              PID=$(cat eureka.pid)
+
+              if kill -0 "$PID" 2>/dev/null; then
+                echo "Deteniendo Eureka con PID $PID..."
+                kill "$PID"
+                sleep 5
+              else
+                echo "El proceso anterior ya no está ejecutándose."
+              fi
+
+              rm -f eureka.pid
+            else
+              echo "No existe un proceso anterior de Eureka."
+            fi
+
+            echo "Iniciando Eureka..."
+
+            nohup java -jar cl-triskeledu-eureka-1.0-SNAPSHOT.jar \
+              --spring.profiles.active=prod \
+              > eureka.log 2>&1 &
+
+            echo $! > eureka.pid
+
+            echo "Esperando que Eureka inicie..."
+            sleep 10
+
+            if kill -0 "$(cat eureka.pid)" 2>/dev/null; then
+              echo "Eureka está ejecutándose correctamente."
+            else
+              echo "ERROR: Eureka no pudo iniciarse."
+              echo "Mostrando últimos logs:"
+              tail -n 50 eureka.log
+              exit 1
+            fi
+
+
+      # 6. Copiar ms-usuarios a AWS
       - name: Copiar ms-usuarios
         uses: appleboy/scp-action@v0.1.7
         with:
@@ -48,7 +109,7 @@ jobs:
           strip_components: 3
 
 
-      # 5. Preparar y ejecutar ms-usuarios en AWS
+      # 7. Preparar y ejecutar ms-usuarios en AWS
       - name: Preparar y ejecutar ms-usuarios
         uses: appleboy/ssh-action@v1.2.2
 
@@ -180,64 +241,77 @@ jobs:
               exit 1
 
             fi
-
-      # 6. Copiar Eureka a AWS
-      - name: Copiar Eureka
+      # 8. Copiar ms-catalogo a AWS
+      - name: Copiar ms-catalogo
         uses: appleboy/scp-action@v0.1.7
         with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_KEY }}
           port: ${{ secrets.SSH_PORT }}
-          source: "Biblioteca-Springboot/eureka/target/cl-triskeledu-eureka-1.0-SNAPSHOT.jar"
+          source: "Biblioteca-Springboot/ms-catalogo/target/cl-triskeledu-catalogo-0.0.1-SNAPSHOT.jar"
           target: "/home/ubuntu/Deploy"
           strip_components: 3
 
-      # 7. Preparar y ejecutar Eureka
-      - name: Preparar y ejecutar Eureka
+
+      # 9. Preparar y ejecutar ms-catalogo
+      - name: Preparar y ejecutar ms-catalogo
         uses: appleboy/ssh-action@v1.2.2
+        env:
+          DB_URL: ${{ secrets.DB_URL }}
+          DB_USERNAME: ${{ secrets.DB_USERNAME }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_KEY }}
           port: ${{ secrets.SSH_PORT }}
+          envs: DB_URL,DB_USERNAME,DB_PASSWORD
           script: |
             cd /home/ubuntu/Deploy
 
-            echo "Deteniendo Eureka anterior..."
+            echo "Deteniendo ms-catalogo anterior..."
 
-            if [ -f eureka.pid ]; then
-              PID=$(cat eureka.pid)
+            if [ -f ms-catalogo.pid ]; then
+              PID=$(cat ms-catalogo.pid)
 
               if kill -0 "$PID" 2>/dev/null; then
-                echo "Deteniendo Eureka con PID $PID..."
+                echo "Deteniendo proceso anterior con PID $PID..."
                 kill "$PID"
                 sleep 5
               else
                 echo "El proceso anterior ya no está ejecutándose."
               fi
 
-              rm -f eureka.pid
+              rm -f ms-catalogo.pid
             else
-              echo "No existe un proceso anterior de Eureka."
+              echo "No existe un proceso anterior."
             fi
 
-            echo "Iniciando Eureka..."
+            export DB_URL="$DB_URL"
+            export DB_USERNAME="$DB_USERNAME"
+            export DB_PASSWORD="$DB_PASSWORD"
 
-            nohup java -jar cl-triskeledu-eureka-1.0-SNAPSHOT.jar \
+            export EUREKA_URL="http://localhost:8761/eureka"
+
+            echo "Iniciando ms-catalogo..."
+
+            nohup java -jar cl-triskeledu-catalogo-0.0.1-SNAPSHOT.jar \
               --spring.profiles.active=prod \
-              > eureka.log 2>&1 &
+              > ms-catalogo.log 2>&1 &
 
-            echo $! > eureka.pid
+            echo $! > ms-catalogo.pid
 
-            echo "Esperando que Eureka inicie..."
+            echo "Esperando que Spring Boot inicie..."
             sleep 10
 
-            if kill -0 "$(cat eureka.pid)" 2>/dev/null; then
-              echo "Eureka está ejecutándose correctamente."
+            if kill -0 "$(cat ms-catalogo.pid)" 2>/dev/null; then
+              echo "ms-catalogo está ejecutándose correctamente."
             else
-              echo "ERROR: Eureka no pudo iniciarse."
+              echo "ERROR: ms-catalogo no pudo iniciarse."
               echo "Mostrando últimos logs:"
-              tail -n 50 eureka.log
+              tail -n 50 ms-catalogo.log
               exit 1
             fi
+
+      
